# Generated by Django 4.2.5 on 2023-10-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0002_question_niveau'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='game',
        ),
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
