# Generated by Django 4.2.5 on 2023-10-10 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('joueur', '0003_remove_answer_game_question_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='game',
            name='start_time',
        ),
        migrations.AddField(
            model_name='game',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
